### ISSUE TITLE
Layout issues on design systems page

### ISSUE THREAD

**Issue by bmcorum** [USAJOBS/design-system#85] opened 2016-05-27 12:57 UTC
Found a couple pages that are functioning differently from the rest of the pages. I have spent sometime trying to determine why these pages function differently, but I not sure exactly how the IO site is being built and structured....maybe I am missing something. Would be more than glad to help, but for now here are the pages that seem to be functioning improperly....at least in Chrome

http://usajobs.github.io/design-system/shell/
http://usajobs.github.io/design-system/grid/

**Comment by humancompanion** [comment] 2016-05-31 14:47
@bmcorum - I believe the problem is that those pages don't have their contents absolutely positioned like the other pages of the system. That absolute positioning is there to deal with the fixed menu. We inherited these styles from the USWDS. The shell and grid pages don't demonstrate those parts of the design system with that positioning in place. 

This was a good prompt for me to replace that default navbar on those pages. I just deployed a fix. Can you check out those pages and close this issue if you feel the changes I made addressed the problem you were seeing? Thanks.

**Closed** 2016-05-31 14:59 UTC
